### ISSUE TITLE
TypeError: fn.apply is not a function

### ISSUE THREAD

**Issue by momosh** [koa-modules/multer#12]
Got the same error with using both Koa-v1.x and Koa-v2.x. Also tried koa-router and koa-route, and usage example to no avail. This is the error I get:
  TypeError: fn.apply is not a function
      at Object.<anonymous> (E:\Sites\test\node_modules\koa-route\index.js:34:19)
      at next (native)
      at onFulfilled (E:\Sites\test\node_modules\co\index.js:65:19)
      at E:\Sites\test\node_modules\co\index.js:54:5
      at Object.co (E:\Sites\test\node_modules\co\index.js:50:10)
      at converted (E:\Sites\test\node_modules\koa-convert\index.js:17:15)
      at dispatch (E:\Sites\test\node_modules\koa\node_modules\koa-compose\index.js:44:32)
      at E:\Sites\test\node_modules\koa\node_modules\koa-compose\index.js:36:12
      at Server.<anonymous> (E:\Sites\test\node_modules\koa\lib\application.js:136:7)
      at emitTwo (events.js:106:13)

(node:4212) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'headers' of undefined

**Comment by Sunshine168** [comment]
I have same question

**Comment by fundon** [comment]
Try koa v2 + koa-multer v1.0.1.
