### ISSUE TITLE
Multer crashes node (Cannot read property 'headers' of undefined)

### ISSUE THREAD

**Issue by jaredreich** [koa-modules/multer#9]
Koa and multer cause node to crash because `req.headers` is undefined.

The error happens here (node_modules/type-is/index.js:93:13):
```js
function hasbody (req) {
  return req.headers['transfer-encoding'] !== undefined ||
    !isNaN(req.headers['content-length'])
}
```

My simple node code:
```js
const router = require('koa-router')()
const multer = require('koa-multer')
const upload = multer({ dest: 'uploads/' })

router.post('/files', upload.any(), function (next) {
   console.log(this.request)
   this.body = 'done'
})
```

When a the multipart request arrives at the endpoint, this error is thrown:
```
API Error { TypeError: Cannot read property 'headers' of undefined
    at hasbody (/Users/John/test/node_modules/type-is/index.js:93:13)
    at typeofrequest (/Users/John/test/node_modules/type-is/index.js:127:8)
    at multerMiddleware (/Users/John/test/node_modules/multer/lib/make-middleware.js:18:10)
    at Promise (/Users/John/test/node_modules/koa-multer/index.js:32:33)
    at Object.<anonymous> (/Users/John/test/node_modules/koa-multer/index.js:31:14)
    at Object.dispatch (/Users/John/test/node_modules/koa-router/lib/router.js:329:52)
    at next (native)
    at onFulfilled (/Users/John/test/node_modules/co/index.js:65:19)
    at /Users/John/test/node_modules/co/index.js:54:5
    at Object.co (/Users/John/test/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/John/test/node_modules/co/index.js:118:63)
    at next (/Users/John/test/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/John/test/node_modules/co/index.js:69:7)
    at /Users/John/test/node_modules/co/index.js:54:5
    at Object.co (/Users/John/test/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/John/test/node_modules/co/index.js:118:63)
```

Does this have to do with Koa changing `req` to `this.request`?

**Comment by mezod** [comment]
For anyone stumbling upon this, I also had this error and it's because I was using koa-multer 1.x with koa 1.x. For those using koa 1.x, you need to use koa-multer 0.x
